/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasigudang;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;

/**
 *
 * @author syffmhr
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Aplikasi Gudang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Syiffa Ocktavia Asmariyadi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setText("2210010548");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 23, 6);
        jPanel1.add(jLabel3, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Master");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Barang");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Supplier");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setText("Barang Masuk/Keluar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setText("Laporan Barang");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setText("Laporan Supplier");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setText("Laporan Transaksi");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Membuka JFrame BarangForm
        BarangForm barangForm = new BarangForm();
        barangForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // Membuka JFrame SupplierForm
        SupplierForm supplierForm = new SupplierForm();
        supplierForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // Membuka JFrame TransaksiForm
        TransaksiForm transaksiForm = new TransaksiForm();
        transaksiForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            // Koneksi ke database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_gudang", "root", "");

            // Buat objek PdfPTable
            PdfPTable table = new PdfPTable(5);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);

            // Tambahkan kolom ke tabel
            PdfPCell cell = new PdfPCell(new Phrase("Kode Barang", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Nama  Barang", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Kategori", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Stok", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Harga", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            // Tambahkan data barang ke tabel
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM barang");

            while (rs.next()) {
                table.addCell(rs.getString("kode_barang"));
                table.addCell(rs.getString("nama_barang"));
                table.addCell(rs.getString("kategori_barang"));
                table.addCell(String.valueOf(rs.getInt("stok")));
                table.addCell(rs.getString("harga"));
            }

            rs.close();
            stmt.close();

            // Buat objek PdfP
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, new FileOutputStream("laporan_barang.pdf"));
            document.open();

            // Tambahkan judul laporan
            document.add(new Paragraph("Laporan Barang", new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD)));

            // Tambahkan tabel ke dokumen
            document.add(table);

            document.close();

            // Membuka file PDF secara langsung
            Desktop.getDesktop().open(new File("laporan_barang.pdf"));

            JOptionPane.showMessageDialog(null, "Laporan barang telah dibuat!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            // Koneksi ke database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_gudang", "root", "");

            // Buat objek PdfPTable
            PdfPTable table = new PdfPTable(6);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);

            // Tambahkan kolom ke tabel
            PdfPCell cell = new PdfPCell(new Phrase("No", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Kode Barang", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Kode Supplier", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Tanggal", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Jumlah", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Tipe Transaksi", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            // Tambahkan data transaksi ke tabel
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM transaksi");

            while (rs.next()) {
                table.addCell(String.valueOf(rs.getInt("id_transaksi")));
                table.addCell(rs.getString("kode_barang"));
                table.addCell(rs.getString("kode_supplier"));
                table.addCell(rs.getString("tanggal"));
                table.addCell(String.valueOf(rs.getInt("jumlah")));
                table.addCell(rs.getString("tipe_transaksi"));
            }

            rs.close();
            stmt.close();

            // Buat objek PdfP
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, new FileOutputStream("laporan_transaksi.pdf"));
            document.open();

            // Tambahkan judul laporan
            document.add(new Paragraph("Laporan Transaksi", new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD)));

            // Tambahkan tabel ke dokumen
            document.add(table);

            document.close();

            // Membuka file PDF secara langsung
            Desktop.getDesktop().open(new File("laporan_transaksi.pdf"));

            JOptionPane.showMessageDialog(null, "Laporan transaksi telah dibuat!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            // Koneksi ke database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_gudang", "root", "");

            // Buat objek PdfPTable
            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);

            // Tambahkan kolom ke tabel
            PdfPCell cell = new PdfPCell(new Phrase("Kode Supplier", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Nama", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Alamat", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            cell = new PdfPCell(new Phrase("Telepon", new Font(Font.FontFamily.HELVETICA, 15, Font.BOLD)));
            table.addCell(cell);

            // Tambahkan data supplier ke tabel
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM supplier");

            while (rs.next()) {
                table.addCell(rs.getString("kode_supplier"));
                table.addCell(rs.getString("nama_supplier"));
                table.addCell(rs.getString("alamat_supplier"));
                table.addCell(rs.getString("kontak_supplier"));
            }

            rs.close();
            stmt.close();

            // Buat objek PdfP
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, new FileOutputStream("laporan_supplier.pdf"));
            document.open();

            // Tambahkan judul laporan
            document.add(new Paragraph("Laporan Supplier", new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD)));

            // Tambahkan tabel ke dokumen
            document.add(table);

            document.close();

            // Membuka file PDF secara langsung
            Desktop.getDesktop().open(new File("laporan_supplier.pdf"));

            JOptionPane.showMessageDialog(null, "Laporan supplier telah dibuat!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
